[package]
name = "dicti0nary-attack-generators"
version = "0.1.0"
edition = "2021"

[dependencies]
dicti0nary-attack-core = { path = "../core" }
rand = { workspace = true }
serde = { workspace = true }
